name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.22']
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}
        cache: true

    - name: Verify code quality
      run: go vet ./...
      
    - name: Build library
      run: go build -v ./...
      if: success()
      
    - name: Verify basic example builds
      run: go build -v ./examples/basic
      if: success()
      
    - name: Verify advanced example builds
      run: go build -v ./examples/advanced
      if: success()

    - name: Run tests with race detection
      if: success()
      run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

    - name: Run examples via script
      if: success()
      run: |
        chmod +x ./scripts/run_examples.sh
        ./scripts/run_examples.sh
      
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}